### ISSUE TITLE
Unable to open web interface for frontend after running install instructions

### ISSUE THREAD

**Issue by DrDab** [Monacr/FitSocial#12]
**Describe the bug**
After running `npm start` in the `frontend` directory, Node crashes with the following message: 
```
Error: Cannot find module '@expo/config/paths'
Require stack:
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack/index.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack.config.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/webpack/resolveFromProject.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/index.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/bin/cli
Error: Cannot find module '@expo/config/paths'
Require stack:
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack/index.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack.config.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/webpack/resolveFromProject.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/startAsync.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/src/start/index.js
- /home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/cli/build/bin/cli
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack/index.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/husky/Documents/courses/cse403/FitSocial/frontend/node_modules/@expo/webpack-config/webpack.config.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
```

**To Reproduce**
Whether the bug can be reproduced at will, occasionally, or not at all
1. Go to `frontend`
2. Run `npm i`
3. Run `npm start`
4. Press W key
5. See error

**Expected behavior**
A web browser window opens up with the Expo frontend application visible in the web interface.

**Actual behavior**
Node crashed and gave me the previously-described error message.

**Additional context**
The error can be fixed by running the command: `npm install expo-cli`

**Comment by yingfc** [comment]
same [here](https://github.com/Monacr/FitSocial/issues/13)

**Comment by Lawqup** [comment]
Running in the web is no longer supported. I've updated the README to indicate this. For more information see #13.
