### ISSUE TITLE
Backend rust build failure 

### ISSUE THREAD

**Issue by linqiu0-0** [Monacr/FitSocial#17]
**Describe the bug**
I follow the steps in the README.md to start the backend service, but it build failed. 

**To Reproduce**
Install the Rust with the default installation method. My rust version is `rustc 1.69.0-nightly (7281249a1 2023-02-27).`
1. Go to backend folder
2. Run `rustup default nightly`. Then see 
```(base) qiulin@qiulindeMacBook-Pro-2 backend % rustup default nightly

info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.69.0-nightly (7281249a1 2023-02-27)
```
3. Run `cargo run`5. 
The see error 
```(base) qiulin@qiulindeMacBook-Pro-2 backend % cargo run

   Compiling rquickjs-sys v0.1.7
   Compiling anyhow v1.0.69
   Compiling async-trait v0.1.64
   Compiling proc-macro-error-attr v1.0.4
   Compiling num-integer v0.1.45
   Compiling cookie v0.11.5
   Compiling serde_urlencoded v0.7.1
   Compiling sha2 v0.10.6
   Compiling mime_guess v2.0.4
   Compiling want v0.3.0
error: failed to run custom build command for `rquickjs-sys v0.1.7`

Caused by:
  process didn't exit successfully: `/Users/qiulin/Desktop/cse403/FitSocial/backend/target/debug/build/rquickjs-sys-14f68b262b11072d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT
  Appliyng patch patches/check_stack_overflow.patch
  patching file quickjs.c
  Appliyng patch patches/infinity_handling.patch
  patching file quickjs.c
  Hunk #1 succeeded at 10235 (offset 44 lines).
  Hunk #2 succeeded at 41732 (offset 168 lines).
  Hunk #3 succeeded at 47839 (offset 168 lines).
  Appliyng patch patches/atomic_new_class_id.patch
  patching file quickjs.c
  Hunk #1 succeeded at 3371 (offset 18 lines).
  Appliyng patch patches/read_module_exports.patch
  patching file quickjs.c
  Hunk #1 succeeded at 27254 (offset 93 lines).
  patching file quickjs.h
  Hunk #1 succeeded at 1039 (offset 4 lines).

  --- stderr
  Apple clang version 12.0.0 (clang-1200.0.32.28)
  Target: aarch64-apple-darwin
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/qiulin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.60.1/src/ir/context.rs:529:15
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
**Expected behavior**
The backend should work 

**Actual behavior**
See error above 

**Additional text**
`cargo test` command does not work due to a similar build failure.

**Comment by Lawqup** [comment]
This looks pretty similar to #16 but may not be it. Try looking at the fixes there and tell me if it works.

**Comment by linqiu0-0** [comment]
Hmmm. That one asks to download patch for the window system, but I am using mac

**Comment by Lawqup** [comment]
Can you run with `RUST_BACKTRACE=1` so we can see the backtrace?

**Comment by linqiu0-0** [comment]
> Can you run with `RUST_BACKTRACE=1` so we can see the backtrace?

Here are the backtrace.
```
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:64:14
     2: core::panicking::panic_display
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:147:5
     3: core::panicking::panic_str
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:131:5
     4: core::option::expect_failed
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/option.rs:1926:5
     5: core::option::Option<T>::expect
     6: bindgen::ir::context::BindgenContext::new
     7: bindgen::Bindings::generate
     8: bindgen::Builder::generate
     9: build_script_build::bindgen
    10: build_script_build::main
    11: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by linqiu0-0** [comment]
This is the full backtrace 
```
qiulin@qiulindeMacBook-Pro-2 backend % cargo run
   Compiling rquickjs-sys v0.1.7
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling zstd-sys v2.0.7+zstd.1.5.4
   Compiling cookie v0.11.5
   Compiling hkdf v0.12.3
   Compiling want v0.3.0
   Compiling approx v0.5.1
   Compiling rocket v0.4.11
   Compiling rand_xoshiro v0.6.0
   Compiling errno v0.2.8
   Compiling atty v0.2.14
   Compiling atomic v0.5.1
   Compiling multer v2.0.4
   Compiling figment v0.10.8
   Compiling rustversion v1.0.11
error: failed to run custom build command for `rquickjs-sys v0.1.7`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/qiulin/Desktop/cse403/FitSocial/backend/target/debug/build/rquickjs-sys-14f68b262b11072d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT
  Appliyng patch patches/check_stack_overflow.patch
  patching file quickjs.c
  Appliyng patch patches/infinity_handling.patch
  patching file quickjs.c
  Hunk #1 succeeded at 10235 (offset 44 lines).
  Hunk #2 succeeded at 41732 (offset 168 lines).
  Hunk #3 succeeded at 47839 (offset 168 lines).
  Appliyng patch patches/atomic_new_class_id.patch
  patching file quickjs.c
  Hunk #1 succeeded at 3371 (offset 18 lines).
  Appliyng patch patches/read_module_exports.patch
  patching file quickjs.c
  Hunk #1 succeeded at 27254 (offset 93 lines).
  patching file quickjs.h
  Hunk #1 succeeded at 1039 (offset 4 lines).

  --- stderr
  Apple clang version 12.0.0 (clang-1200.0.32.28)
  Target: aarch64-apple-darwin
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/qiulin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.60.1/src/ir/context.rs:529:15
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:64:14
     2: core::panicking::panic_display
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:147:5
     3: core::panicking::panic_str
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:131:5
     4: core::option::expect_failed
               at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/option.rs:1926:5
     5: core::option::Option<T>::expect
     6: bindgen::ir::context::BindgenContext::new
     7: bindgen::Bindings::generate
     8: bindgen::Builder::generate
     9: build_script_build::bindgen
    10: build_script_build::main
    11: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
(base) qiulin@qiulindeMacBook-Pro-2 backend % export RUST_BACKTRACE=full
(base) qiulin@qiulindeMacBook-Pro-2 backend % cargo run
   Compiling rquickjs-sys v0.1.7
   Compiling semver v1.0.16
   Compiling imbl v1.0.1
   Compiling atomic v0.5.1
   Compiling multer v2.0.4
   Compiling rustversion v1.0.11
   Compiling figment v0.10.8
   Compiling rustix v0.36.8
   Compiling geo-types v0.7.8
   Compiling rocket v0.4.11
error: failed to run custom build command for `rquickjs-sys v0.1.7`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/qiulin/Desktop/cse403/FitSocial/backend/target/debug/build/rquickjs-sys-14f68b262b11072d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT
  Appliyng patch patches/check_stack_overflow.patch
  patching file quickjs.c
  Appliyng patch patches/infinity_handling.patch
  patching file quickjs.c
  Hunk #1 succeeded at 10235 (offset 44 lines).
  Hunk #2 succeeded at 41732 (offset 168 lines).
  Hunk #3 succeeded at 47839 (offset 168 lines).
  Appliyng patch patches/atomic_new_class_id.patch
  patching file quickjs.c
  Hunk #1 succeeded at 3371 (offset 18 lines).
  Appliyng patch patches/read_module_exports.patch
  patching file quickjs.c
  Hunk #1 succeeded at 27254 (offset 93 lines).
  patching file quickjs.h
  Hunk #1 succeeded at 1039 (offset 4 lines).

  --- stderr
  Apple clang version 12.0.0 (clang-1200.0.32.28)
  Target: aarch64-apple-darwin
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/qiulin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.60.1/src/ir/context.rs:529:15
  stack backtrace:
     0:        0x101053c2c - std::backtrace_rs::backtrace::libunwind::trace::ha3a69d427960173b
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x101053c2c - std::backtrace_rs::backtrace::trace_unsynchronized::h0f0ce0a207da8012
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x101053c2c - std::sys_common::backtrace::_print_fmt::hed9ab37717521022
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:65:5
     3:        0x101053c2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb3ddbfd12443ce3b
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x10106fba8 - core::fmt::write::h869231813cb16a41
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/fmt/mod.rs:1232:17
     5:        0x101050288 - std::io::Write::write_fmt::h7899fdedcb8db66c
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/io/mod.rs:1684:15
     6:        0x101053a40 - std::sys_common::backtrace::_print::h423805e4f80cfac6
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:47:5
     7:        0x101053a40 - std::sys_common::backtrace::print::h73bf653bccd09073
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:34:9
     8:        0x1010556e0 - std::panicking::default_hook::{{closure}}::hde087248b6557213
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:271:22
     9:        0x101055438 - std::panicking::default_hook::hb333432533213361
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:290:9
    10:        0x101055bf0 - std::panicking::rust_panic_with_hook::h8a1dc95273805915
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:692:13
    11:        0x101055b24 - std::panicking::begin_panic_handler::{{closure}}::h63b1f0a79a3ceb36
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:583:13
    12:        0x10105404c - std::sys_common::backtrace::__rust_end_short_backtrace::h4779713f335d9d9c
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/sys_common/backtrace.rs:137:18
    13:        0x101055880 - rust_begin_unwind
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:579:5
    14:        0x10108441c - core::panicking::panic_fmt::h5014f4f1f12ddd8c
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:64:14
    15:        0x10106e3dc - core::panicking::panic_display::h886eff031240ad2d
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:147:5
    16:        0x10106e3a0 - core::panicking::panic_str::h4548c2dcf21ee4e4
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/panicking.rs:131:5
    17:        0x1010843e8 - core::option::expect_failed::h0861dde0131f2426
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/option.rs:1926:5
    18:        0x100d84ed8 - core::option::Option<T>::expect::ha22d894a2c8312b3
    19:        0x100dab128 - bindgen::ir::context::BindgenContext::new::hdc381cd432260bc0
    20:        0x100d7793c - bindgen::Bindings::generate::h2c94e825343a990c
    21:        0x100d75a24 - bindgen::Builder::generate::h2db561b915d452b9
    22:        0x100ca13d4 - build_script_build::bindgen::hc8940f4136158530
    23:        0x100ca0614 - build_script_build::main::h6d7c5100249742a4
    24:        0x100c9e98c - core::ops::function::FnOnce::call_once::heb8b5bea1f99c2e5
    25:        0x100c9dd74 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51849ab6205ff8a0
    26:        0x100c9ee14 - std::rt::lang_start::{{closure}}::h9777d7711e84f8ec
    27:        0x10104c090 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbc930cd6447216bb
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/core/src/ops/function.rs:287:13
    28:        0x10104c090 - std::panicking::try::do_call::ha16f9131a6d1e1f1
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:487:40
    29:        0x10104c090 - std::panicking::try::h38485b814c28ad40
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:451:19
    30:        0x10104c090 - std::panic::catch_unwind::hcb02fd5107bf07d0
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panic.rs:140:14
    31:        0x10104c090 - std::rt::lang_start_internal::{{closure}}::hb14ed90c55026339
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/rt.rs:148:48
    32:        0x10104c090 - std::panicking::try::do_call::h0901f551c87ae678
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:487:40
    33:        0x10104c090 - std::panicking::try::h93a05c2797a1924f
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panicking.rs:451:19
    34:        0x10104c090 - std::panic::catch_unwind::he6301f711f81fd89
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/panic.rs:140:14
    35:        0x10104c090 - std::rt::lang_start_internal::h0f89d2816fdbf27b
                                 at /rustc/7281249a19a9755e9d889ee251ec323629caadab/library/std/src/rt.rs:148:20
    36:        0x100c9edec - std::rt::lang_start::h57690d3e42098386
    37:        0x100ca1748 - _main

```

**Comment by Lawqup** [comment]
I still think this could be a problem with rquickjs. See if you can install/reinstall rquickjs or patch for Mac.

**Comment by linqiu0-0** [comment]
Work after run `cargo add rquickjs`
Follow this tutorial  https://crates.io/crates/rquickjs
