### ISSUE TITLE
Frontend npm install failed

### ISSUE THREAD

**Issue by linqiu0-0** [Monacr/FitSocial#18]
**Describe the bug**
`npm i` command failed with error. 

**To Reproduce**
Whether the bug can be reproduced at will, occasionally, or not at all
1. Go to frontend directory
2. run `npm i`
3. See error
```
(base) qiulin@qiulindeMacBook-Pro-2 frontend % npm i    

> fsevents@1.2.13 install /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.13 install /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> styled-components@5.3.6 postinstall /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/styled-components
> node ./postinstall.js


> react-native-localhost@1.0.0 postinstall /Users/qiulin/Desktop/cse403/FitSocial/frontend/node_modules/react-native-localhost
> node scripts/postinstall

added 1997 packages from 957 contributors and audited 2000 packages in 21.23s

140 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (2 low, 3 moderate, 11 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
**Expected behavior**
The frontend npm install should not return an error.

**Actual behavior**
Do I need to download some extra dependency to run this app? such as Xcode?
**Additional context**

**Comment by Lawqup** [comment]
Try installing Xcode and see if that fixes the problem. It's not a dependency directly but I think npm (or Expo) looks for it to run the emulator.

**Comment by linqiu0-0** [comment]
Have u installed Xcode before? which version are you using

**Comment by Lawqup** [comment]
I'm using Linux so I don't have access to Xcode. I don't think the version matters so use the latest (stable) version. Some team members are using mac but they have Xcode installed so that might be the issue.

**Comment by linqiu0-0** [comment]
Npm install works after installing Xcode! Thanks!
But there are new issues in the npm start part :( I might need to file a new issue if I could not resolve it by myself.
